name: Lint Pull Request


on:
  pull_request_target:
    types:
      - edited
      - opened
      - synchronize


permissions:
  pull-requests: read


jobs:
  lint-pull-request:
    runs-on: ubuntu-latest
    name: Validate pull request title

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
