name: Release


on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+'


permissions:
  contents: write


jobs:
  build-distribution:
    runs-on: ubuntu-latest
    name: Build Python distribution

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ">=3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/


  publish-to-pypi:
    runs-on: ubuntu-latest
    name: Publish Python distribution to PyPI

    needs:
      - build-distribution

    environment:
      name: pypi
      url: https://pypi.org/p/pythontooltemplate

    permissions:
      id-token: write

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish distribution
        uses: pypa/gh-action-pypi-publish@release/v1

  publish-release:
    runs-on: ubuntu-latest
    name: Publish release

    needs:
      - build-distribution

    steps:
      - name: Set environment variables
        run: |
          echo "CHANGELOG=CHANGELOG.md" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate changelog
        uses: tj-actions/git-cliff@v1
        with:
          args: --verbose
          output: ${{ env.CHANGELOG }}
          template-config: .github/cliff_template.toml

      - name: Commit changelog
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.CHANGELOG }}
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: Update ${{ env.CHANGELOG }}
          push: origin HEAD:main v${{ env.VERSION }} --force
          tag: v${{ env.VERSION }} -fam "version ${{ env.VERSION }}"

      - name: Download the distribution packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Create GitHub release
        uses: docker://antonyurchenko/git-release:latest
        with:
          args:
            ./dist/*.whl
